name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup tools
      run: sudo apt-get install gcc-arm-linux-gnueabihf dtc
    - name: config
      run: make snappermx6_defconfig CROSS_COMPILE=arm-linux-gnueabihf-
    - name: build
      run: make -j u-boot.imx CROSS_COMPILE=arm-linux-gnueabihf-
